[package]
name = "PROJECT_NAME"
version = "0.1.0"
authors = ["anon <anon@anon.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
